### ISSUE TITLE
Incorrect FFI binding for `cephes_double::sici`

### ISSUE THREAD

**Issue by icmccorm** [vks/special-fun#14]
The Rust binding for the function `cephes_double::sici` indicates that it returns an `f64`
```
pub fn sici(x: f64, si: &mut f64, ci: &mut f64) -> f64;
```
However, the corresponding C function in [sici.c](https://github.com/vks/special-fun/blob/master/cephes-double/sici.c) returns a 32-bit integer:
```
int sici( x, si, ci )
double x;
double *si, *ci;
{
...
```

**Comment by vks** [comment]
Thanks! Since the return value is always 0, I'll just remove the return type from the high-level bindings, and fix the low-level bindings.
