### ISSUE TITLE
Put a big bold warning in the readme

### ISSUE THREAD

**Issue by dspyz-matician** [vks/special-fun#15]
This crate introduces completely unmangled C function names that override the standard ones in libc, including sin and cos. This means simply depending on this crate _anywhere_, even transitively overrides all the basic math operations in the standard library with its own implementations (this is similar to a major part of how the xz utils backdoor worked).

**Comment by vks** [comment]
I'm not sure it affects the standard library as you say, because AFAIK it uses LLVM primitives for math, and not necessarily libc. But it's a fair point! We unfortunately inherit this from upstream Cephes.

**Comment by vks** [comment]
@dspyz-matician I updated the README, does the wording work for you?

**Comment by dspyz-matician** [comment]
Looks great! Thanks!
