### ISSUE TITLE
Adding support for the Lambert W function? 

### ISSUE THREAD

**Issue by JSorngard** [vks/special-fun#16]
I recently finished [an implementation](https://crates.io/crates/lambert_w) of [Toshio Fukushima's method](https://www.researchgate.net/publication/346309410_Precise_and_fast_computation_of_Lambert_W_function_by_piecewise_minimax_rational_function_approximation_with_variable_transformation) for evaluating the [Lambert W function](https://en.wikipedia.org/wiki/Lambert_W_function). Would it be interesting to add this capability to this crate?

**Comment by JSorngard** [comment]
Oh right, you bind to Cephes, so using a rust dependency might not align with the design goal of this crate.

**Comment by vks** [comment]
Yes, it would probably make more sense to add it to another crate featuring Rust implementations of special functions, e.g. `special`.
