### ISSUE TITLE
The `-march=native` flag in the cephes Makefiles can be problematic; compile using `gcc` crate?

### ISSUE THREAD

**Issue by pkgw** [vks/special-fun#3]
OK, this is a pretty esoteric issue, but it is currently causing me problems.

I am trying to use special-fun in some code that I want to run on large compute cluster. However, the cephes Makefiles invoked by the `build.rs` script have some hardcoded compiler flags that include `-march=native`. For the compilers that I have to use, this leads to code that uses AVX instructions. However, many of the nodes on my cluster do not actually support AVX, so the generated binaries will not run on those nodes. I do not see a way to override this compiler setting given the way that this package builds the C code.

If the C code were built using the `gcc` crate, it would be possible to pass flags to the C compiler through the `CFLAGS` environment variable, if nothing else. I believe that it would also work to patch the Makefiles to use the `?=` assignment operator for variables like `CFLAGS`.

**Comment by vks** [comment]
I agree that a hardcoded `-march=native` is problematic. I will look into this.

If you were able to build on your nodes, you could work around this.

**Comment by vks** [comment]
6c292b5056 should fix this by dropping `-march=native` and making it possible to overwrite `CFLAGS` via the environment.

**Comment by tmarkovich** [comment]
I believe this can be closed now.

**Comment by pkgw** [comment]
Would it be possible to publish a new release to crates.io so that my downstream projects can depend on a version that includes this fix?

**Comment by vks** [comment]
@pkgw Of course, I just published version 0.1.6.

**Comment by pkgw** [comment]
@vks Thanks!
