### ISSUE TITLE
msvc

### ISSUE THREAD

**Issue by nilgoyette** [vks/special-fun#7]
Is this library supposed to work on Windows? I tried building it with (and without) cl.exe in my `PATH`, as required by `cc-rs`. It always return:

    error: failed to run custom build command for `special-fun v0.1.6`
    process didn't exit successfully: `C:\Imeka\nlmeans\target\debug\build\special-fun-012dfdbea798f1e8\build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "Le fichier spécifié est introuvable." } }', src\libcore\result.rs:906:4
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

With `Le fichier spécifié est introuvable.` meaning `Can't find the specified file.` I can't use `RUST_BACKTRACE=1` on Windows and I can't know which file is required.

**Comment by vks** [comment]
Are you building from crates.io? I didn't publish the version that replaces `make` with the `cc` crate yet, so I would not expect it to work on windows. Could you try using the git master and see whether it works?

**Comment by nilgoyette** [comment]
I tested with

    special-fun = { git = "https://github.com/vks/special-fun.git" }

and I have this error now.

    error: failed to run custom build command for `special-fun v0.1.6 (https://github.com/vks/special-fun.git#943599c7)`
    process didn't exit successfully: `C:\nlmeans\target\release\build\special-fun-e7c66827372010c9\build-script-build` (exit code: 101)
    --- stdout
    TARGET = Some("x86_64-pc-windows-msvc")
    OPT_LEVEL = Some("3")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CC_x86_64-pc-windows-msvc = None
    CC_x86_64_pc_windows_msvc = None
    HOST_CC = None
    CC = None
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CFLAGS_x86_64-pc-windows-msvc = None
    CFLAGS_x86_64_pc_windows_msvc = None
    HOST_CFLAGS = None
    CFLAGS = None
    DEBUG = Some("false")
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "cephes-double" "/W4" "-Wall" "-fno-builtin" "/FoC:\\nlmeans\\target\\release\\build\\special-fun-9678ea3ff2181444\\out\\cephes-double\\acosh.o" "/c" "cephes-double\\acosh.c"
    cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-fno-builtin'
    acosh.c
    cephes-double\acosh.c(138): warning C4131: 'acosh': uses old-style declarator
    exit code: 0
    TARGET = Some("x86_64-pc-windows-msvc")
    OPT_LEVEL = Some("3")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CC_x86_64-pc-windows-msvc = None
    CC_x86_64_pc_windows_msvc = None
    HOST_CC = None
    CC = None
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CFLAGS_x86_64-pc-windows-msvc = None
    CFLAGS_x86_64_pc_windows_msvc = None
    HOST_CFLAGS = None
    CFLAGS = None
    DEBUG = Some("false")
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "cephes-double" "/W4" "-Wall" "-fno-builtin" "/FoC:\\nlmeans\\target\\release\\build\\special-fun-9678ea3ff2181444\\out\\cephes-double\\airy.o" "/c" "cephes-double\\airy.c"
    cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-fno-builtin'
    airy.c
    cephes-double\airy.c(839): warning C4131: 'airy': uses old-style declarator
    exit code: 0
    TARGET = Some("x86_64-pc-windows-msvc")
    OPT_LEVEL = Some("3")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CC_x86_64-pc-windows-msvc = None
    CC_x86_64_pc_windows_msvc = None
    HOST_CC = None
    CC = None
    TARGET = Some("x86_64-pc-windows-msvc")
    HOST = Some("x86_64-pc-windows-msvc")
    CFLAGS_x86_64-pc-windows-msvc = None
    CFLAGS_x86_64_pc_windows_msvc = None
    HOST_CFLAGS = None
    CFLAGS = None
    DEBUG = Some("false")
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "cephes-double" "/W4" "-Wall" "-fno-builtin" "/FoC:\\nlmeans\\target\\release\\build\\special-fun-9678ea3ff2181444\\out\\cephes-double\\asin.o" "/c" "cephes-double\\asin.c"
    cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-fno-builtin'
    asin.c
    cephes-double\asin.c(114): warning C4668: 'DEC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(132): warning C4668: 'IBMPC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(150): warning C4668: 'MIEEE' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(188): warning C4668: 'DEC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(204): warning C4668: 'IBMPC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(220): warning C4668: 'MIEEE' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    cephes-double\asin.c(256): warning C4131: 'asin': uses old-style declarator
    cephes-double\asin.c(256): error C2169: 'asin': intrinsic function, cannot be defined
    cephes-double\asin.c(256): error C2085: 'x': not in formal parameter list
    cephes-double\asin.c(307): warning C4131: 'acos': uses old-style declarator
    cephes-double\asin.c(307): error C2169: 'acos': intrinsic function, cannot be defined
    cephes-double\asin.c(307): error C2085: 'x': not in formal parameter list
    exit code: 2

    --- stderr
    thread 'main' panicked at '

    Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "cephes-double" "/W4" "-Wall" "-fno-builtin" "/FoC:\\nlmeans\\target\\release\\build\\special-fun-9678ea3ff2181444\\out\\cephes-double\\asin.o" "/c" "cephes-double\\asin.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

    ', C:\Users\Nil\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.1\src\lib.rs:1653:4
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

    warning: build failed, waiting for other jobs to finish...
    error: build failed

**Comment by vks** [comment]
It seems like MSVC does not support the `-fno-builtin` flag and then complains that some intrinsics are redefined. That means that either

1. `build.rs` needs to use a different flag for MSVC (googling suggests `/Oi-` instead of `-fno-builtin`), or
2. the Cephes source code has to be modified to use different symbols.

**Comment by vks** [comment]
`special-fun` seems to [build on Appveyor and all but one test pass](https://ci.appveyor.com/project/vks/special-fun/build/1.0.2/job/pi4fx1exqa2abl7x). However, I tried to include the flag mentioned above, could you try again whether it fixes the build for you?

**Comment by nilgoyette** [comment]
Nice, it's building without errors.. I don't use `riemann_zeta` so I'm happy with your fix :) Thank you.

**Comment by vks** [comment]
You're welcome! Glad to hear it works for you.

The test failure is weird, and it only happens for single precision. I'll
look into it some later time.
