### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by nilgoyette** [vks/special-fun#8]
Are you aware if using this library causes a slow startup time? I tested on Windows and Linux, and the simple fact of including it (without `use`-ing it) makes my program ~5 seconds slower.

    special-fun = { git = "https://github.com/vks/special-fun.git" }
    extern crate special_fun;
    // Nothing else, really!

Is Cephes building precomputed tables somewhere? If so, where? I could probably verify each file myself but you probably already have the answer.

**Comment by nilgoyette** [comment]
I tested more and the problem is not actually a "slow startup". It's more of a "slow everything". One of my benchmark includes a 12m job. I include your lib (without using it) and now this job takes 16m. Obviously, I'm puzzled by this! I'll try to create a minimal working example. Do you have any idea what could cause this?

**Comment by vks** [comment]
Not sure, I honestly never tried to use the library for something serious.
Are you compiling with optimizations? How big is the binary?

**Comment by vks** [comment]
I cannot reproduce this. Including or not including this library, or even calling one function does not result in a measurable difference in runtime on my Linux system. What are you measuring? Note that `cargo run` seems to recompile the C code every time.

**Comment by nilgoyette** [comment]
I'm compiling with `--release` and testing with the linux `time` command. My linux executable is 6.7Mb. Thank you for the test!

My first thought was to open an issue here because my problem really seems related to this lib. It seems unlikely that a library could do such a thing though. It's probably a mix of several things so I need to test more and to reproduce it with a mwe. I'll close this because I find it hard to believe that a lib can cause this problem :)
